/* ------------------------------------------------------------------
   CATÁLOGO OOMM STUDIO — base de dados das peças
   Cada linha = uma peça.
     c = categoria  ->  chaveiros | displays | brindes | casa | educacionais | festas | religiosos
     n = nome       ->  deixe "" para usar só o código da peça (OOMM-0xx)
     i = número da imagem (img/catalogo/pXX.jpg)
   Use editor-catalogo.html para revisar tudo e reexportar este arquivo.
------------------------------------------------------------------ */
const CATEGORIAS = [
  {id:"todos",        nome:"Tudo"},
  {id:"chaveiros",    nome:"Chaveiros"},
  {id:"displays",     nome:"Displays"},
  {id:"brindes",      nome:"Brindes"},
  {id:"casa",         nome:"Casa"},
  {id:"educacionais", nome:"Educacionais"},
  {id:"festas",       nome:"Brindes de festa"},
  {id:"religiosos",   nome:"Religiosos"}
];

const PRODUTOS = [
  {c:"casa", n:"", i:1},
  {c:"brindes", n:"", i:2},
  {c:"festas", n:"", i:3},
  {c:"casa", n:"", i:4},
  {c:"casa", n:"", i:5},
  {c:"brindes", n:"", i:6},
  {c:"displays", n:"", i:7},
  {c:"chaveiros", n:"", i:8},
  {c:"displays", n:"", i:9},
  {c:"displays", n:"", i:10},
  {c:"casa", n:"", i:11},
  {c:"brindes", n:"", i:12},
  {c:"chaveiros", n:"", i:13},
  {c:"festas", n:"", i:14},
  {c:"educacionais", n:"", i:15},
  {c:"casa", n:"", i:16},
  {c:"brindes", n:"", i:17},
  {c:"displays", n:"", i:18},
  {c:"chaveiros", n:"", i:19},
  {c:"casa", n:"", i:20},
  {c:"festas", n:"", i:21},
  {c:"brindes", n:"", i:22},
  {c:"casa", n:"", i:23},
  {c:"displays", n:"", i:24},
  {c:"chaveiros", n:"", i:25},
  {c:"brindes", n:"", i:26},
  {c:"festas", n:"", i:27},
  {c:"casa", n:"", i:28},
  {c:"displays", n:"", i:29},
  {c:"educacionais", n:"", i:30},
  {c:"chaveiros", n:"", i:31},
  {c:"brindes", n:"", i:32},
  {c:"casa", n:"", i:33},
  {c:"festas", n:"", i:34},
  {c:"displays", n:"", i:35},
  {c:"casa", n:"", i:36},
  {c:"religiosos", n:"", i:37},
  {c:"brindes", n:"", i:38},
  {c:"chaveiros", n:"", i:39},
  {c:"casa", n:"", i:40},
  {c:"casa", n:"", i:41},
  {c:"displays", n:"", i:42},
  {c:"educacionais", n:"", i:43},
  {c:"brindes", n:"", i:44},
  {c:"chaveiros", n:"", i:45},
  {c:"festas", n:"", i:46},
  {c:"casa", n:"", i:47},
  {c:"displays", n:"", i:48},
  {c:"brindes", n:"", i:49},
  {c:"educacionais", n:"", i:50},
  {c:"casa", n:"", i:51},
  {c:"brindes", n:"", i:52},
  {c:"casa", n:"Fidget sensorial", i:53},
  {c:"religiosos", n:"Bandeja Ore e Confie", i:54},
  {c:"festas", n:"", i:55},
  {c:"casa", n:"", i:56},
  {c:"casa", n:"", i:57},
  {c:"brindes", n:"", i:58},
  {c:"casa", n:"", i:59},
  {c:"displays", n:"", i:60},
  {c:"chaveiros", n:"", i:61},
  {c:"festas", n:"", i:62},
  {c:"casa", n:"", i:63},
  {c:"brindes", n:"", i:64},
  {c:"displays", n:"", i:65},
  {c:"casa", n:"", i:66},
  {c:"chaveiros", n:"", i:67},
  {c:"festas", n:"", i:68},
  {c:"brindes", n:"", i:69},
  {c:"casa", n:"", i:70},
  {c:"religiosos", n:"", i:71}
];
